trackWidth: 0.5
ll: 1.2          #小车轴距
ts: 0.125         #规划间隔时间
dt: 0.125
N: 10
qvs: 0.01
v_b: 3.0        #技术要求速度极限3.0m/s
a_b: 0.8        #加速度极限0.8m/s2 
a_brake_b: -2.5  #减速度极限-2.5m/s2
delta_b: 90      #转角极限90°
ddelta_b: 100     #响应速度极限100°/s
vs_b: 3.0
#原地转弯
tip: 0         #转弯角度 值不等于0时自动生成转弯路径
#自定义路径
# track_s   : [1,2,3,4,5,6,7,8,9,10]                     #直线s>=0
# track_r   : [1,2,3,4,5,6,7,8,9,0]                      #转弯半径r>=0
# track_ddeg: [-90,90,-90,90,-90,90,-90,90,-90,0]        #转弯弧度ddeg>=0

# track_s   : [2,2]                     #直线s>=0
# track_r   : [2,0]                      #转弯半径r>0
# track_ddeg: [-90,0]        #转弯弧度ddeg>0

# track_s   : [2,0,0,2]                     #直线s>=0
# track_r   : [2,4,2,0]                      #转弯半径r>0
# track_ddeg: [90,-180,90,0]                   #转弯弧度ddeg>0

track_s   : [2,0,0,2]
track_r   : [2,4,2,0]
track_ddeg: [90,-180,90,0]