track_points_x: [0,  1, 2,3.4, 4, 3.4,  2,  0, -2,-3.4,-4,-3.4,-2,  -1]
track_points_y: [2,  2, 2,1.4, 0,-1.4, -2, -2, -2,-1.4, 0, 1.4, 2,   2]

# track_points_x: [0,0.5, 1,1.7, 2, 1.7,  1,0, -1,-1.7,-2,-1.7,-1,-0.5]
# track_points_y: [1,  1, 1,0.7, 0,-0.7,-1,-1, -1,-0.7, 0, 0.7, 1,   1]


# track_points_x: [-5, -2.5,0, 3]
# track_points_y: [0, 0,0 ,3]